[package]
name = "areweasyncyet"
version = "0.1.0"
authors = ["Xidorn Quan <me@upsuper.org>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
#graphql_client = "0.6.0"
#reqwest = "0.9.6"
lazy_static = "1.2.0"
regex = "1.1.0"
serde = { version = "1.0.84", features = ["derive"] }
serde_yaml = "0.8.8"
tera = "0.11.20"
toml = "0.4.10"
