[package]
name = "areweasyncyet"
version = "0.1.0"
authors = ["Xidorn Quan <me@upsuper.org>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
chrono = "0.4.6"
dotenv = "0.13.0"
env_logger = "0.6.0"
graphql_client = "0.7.0"
lazy_static = "1.2.0"
log = "0.4.6"
matches = "0.1.8"
regex = "1.1.0"
reqwest = "0.9.6"
semver = "0.9.0"
serde = { version = "1.0.84", features = ["derive"] }
serde_derive = "1.0.84"
serde_json = "1.0.38"
serde_with = "1.1.0"
serde_yaml = "0.8.8"
tera = "0.11.20"
